git:
  depth: 1
language: node_js
node_js:
  - '10'
cache:
  yarn: true
install:
  - yarn install
script:
  - yarn eslint .
  - yarn test --coverage
  - bash <(curl -s https://codecov.io/bash) -B $TRAVIS_BRANCH
